linters-settings:
  goimports:
    local-prefixes: "github.com/watarukura/"
  gocritic:
    enabled-tags:
      - performance
  gosimple:
    go: "1.18"
  staticcheck:
    go: "1.18"
  stylecheck:
    go: "1.18"
  unused:
    go: "1.18"

linters:
  enable:
    - deadcode
    - typecheck
    - gofmt
    - goimports
    - gocritic
    - gosec
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign

run:
  timeout: 30m
  skip-dirs:
    - pkg/
  skip-files:
    - "pkg/proto/.*\\.xx\\.go$"

issues:
  exclude-rules: [ ]
